export { default as kindaLooksPlural } from './kinda-looks-plural';
export { default as optionalService } from './optional-service';
export { default as getRootElement } from './get-root-element';
export { default as extractErrorMessages } from './extract-error-messages';
export { default as keyNavigator } from './key-navigator';
export { buildFaClassNameString } from './font-awesome';
export { waitForTransitionEnd } from './transition-end';
export { addAriaAttribute, removeAriaAttribute, getAriaAttributeValues } from './aria';
export { createOutsideClickListener, removeOutsideClickListener } from './outside-click';
export { listenTo } from './computed-macros';
