name: Test

on:
  push:
    branches: ['renovate/*']
    paths-ignore:
      - '**/*.stories.ts'
      - '**/*.stories.mdx'
      - './storybook'
      - './storybook/utilities'
      - './blueprints/**'
      - './README.md'
      - './CONTRIBUTING.md'
      - './.github/workflows/gh-pages.yml'
      - './.github/workflows/release.yml'

  pull_request:
    branches-ignore:
      - 'renovate/*'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  current-dependencies:
    timeout-minutes: 10
    name: Current Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: "sed -i'.bak' -e 's/\"noEmitOnError\": false/\"noEmitOnError\": true/' ./tsconfig.json"
      - run: npm ci --no-audit
      - run: npm run test:coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


  floating-dependencies:
    timeout-minutes: 10
    name: Floating Dependencies
    runs-on: ubuntu-latest
    needs: current-dependencies

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install --no-audit --package-lock=false
      - run: npm test


  try-scenarios:
    timeout-minutes: 10
    name: "Try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    needs: current-dependencies

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-classic
          - ember-default-with-jquery
          - embroider-safe

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: npm ci --no-audit
      - name: test
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
