name: Test

on:
  push:
    branches: ['develop', 'renovate/*']
    paths-ignore:
      - '**/*.stories.ts'
      - '**/*.stories.mdx'
      - './storybook'
      - './storybook/utilities'
      - './blueprints/**'

  pull_request:
    branches-ignore:
      - 'renovate/*'

  workflow_dispatch:

jobs:
  floating-dependencies:
    timeout-minutes: 10
    name: Floating Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: "sed -i'.bak' -e 's/\"noEmitOnError\": false/\"noEmitOnError\": true/' ./tsconfig.json"
      - run: npm install --no-audit --package-lock=false
      - run: npm run test:coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  try-scenarios:
    timeout-minutes: 10
    name: "Try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    needs: test

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-classic
          - ember-default-with-jquery
          - embroider-safe

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: install dependencies
        run: npm ci --no-audit
      - name: test
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
