name: GitHub Pages

on:
  push:
    branches: [ 'main' ]
    paths: [ './addon', './storybook', './storybook-utilities' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
        with:
          node-version: 16.9.0
      - name: Build
        run: |
          npm ci --no-audit
          npm run storybook:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./docs
          force_orphan: true
          publish_branch: gh-pages

