name: Version & Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          npm ci --no-audit
          npm run release -- --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
